# We've moved to GitHub Actions for CI, but these tests have not yet been ported
sudo: required
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
    - enchant
language: python
python:
- '3.6'
env:
  matrix:
  # GitHub Actions does not have AWS credentials
  - CI_PATTERN=tests/test_dcos_e2e/backends/aws/test_aws.py::TestRunIntegrationTest
  - CI_PATTERN=tests/test_dcos_e2e/backends/aws/test_aws.py::TestUnsupported
  - CI_PATTERN=tests/test_dcos_e2e/backends/aws/test_aws.py::TestCustomKeyPair
  - CI_PATTERN=tests/test_dcos_e2e/backends/aws/test_aws.py::TestDCOSInstallation::test_install_dcos_from_path
  - CI_PATTERN=tests/test_dcos_e2e/backends/aws/test_aws.py::TestDCOSInstallation::test_install_dcos_from_node
  - CI_PATTERN=tests/test_dcos_e2e/backends/aws/test_aws.py::TestDCOSInstallation::test_install_dcos_with_custom_ip_detect
  - CI_PATTERN=tests/test_dcos_e2e/backends/aws/test_aws.py::TestDCOSInstallation::test_install_dcos_with_custom_genconf
  - CI_PATTERN=tests/test_dcos_e2e/backends/aws/test_distributions.py::TestCentos7::test_default_distribution
  - CI_PATTERN=tests/test_dcos_e2e/backends/aws/test_distributions.py::TestCentos7::test_set_distribution
  - CI_PATTERN=tests/test_dcos_e2e/backends/aws/test_distributions.py::TestRHEL7::test_oss
  - CI_PATTERN=tests/test_dcos_e2e/backends/aws/test_distributions.py::TestRHEL7::test_enterprise
  - CI_PATTERN=tests/test_dcos_e2e/backends/aws/test_aws.py::TestTags
  # Upgrades run out of diskpace on GitHub Actions
  - CI_PATTERN=tests/test_dcos_e2e/test_cluster.py::TestUpgrade::test_upgrade_from_path
  - CI_PATTERN=tests/test_dcos_e2e/test_cluster.py::TestUpgrade::test_upgrade_from_url
  - CI_PATTERN=tests/test_dcos_e2e/test_node_upgrade.py
before_install:
- sudo modprobe aufs
- sudo modprobe ip6_tables
- echo $LICENSE_KEY_CONTENTS > /tmp/license-key.txt
- travis_retry pip install --upgrade 'pip<20.3' setuptools codecov
- pip uninstall -y six
install:
- travis_retry pip install --upgrade --editable .[dev]
cache: pip
before_script:
- travis_retry make pull-images
- travis_retry python admin/download_installers.py
script:
- python admin/run_script.py
after_success:
- codecov
